const getPlaceholderArrayOfObjects = () => ([
  {
    '#': 1,
    first: 'Mark',
    last: 'Otto',
    handle: '@mdo'
  },
  {
    '#': 2,
    first: 'Jacob',
    last: 'Thornton',
    handle: '@fat'
  },
  {
    '#': 3,
    first: 'Larry',
    last: 'the Bird',
    handle: '@twitter'
  },
])

const getProperties = () => ({
  produto: 'produto',
  carcaca: 'subconjunto carcaca preta',
  kit_reparo: 'subconjunto kit reparo',
  conjunto_magnetico: 'subconjunto conjunto magnético',
  // nucleo_toroidal: 'núcleo de ferrite toroidal 25,3x14,8x20,0mm coated',
  nucleo_toroidal: 'núcleo de ferrite toroidal',
  indutor: 'indutor',
  // nucleo_carretel: 'núcleo ferrite carretel dr2w10x12 d30 10,0x12,0x5,5mm without coat',
  nucleo_carretel: 'núcleo ferrite carretel',
  placa: 'placa',
  capacitor_poliester: 'capacitor pth poliéster 1uf 63v 5%',
  // capacitor_eletrolitico: 'capacitor pth eletrolítico radial 470uf 50v 85g +/- 20% 10x20mm (p.5,0mm) fitado',
  capacitor_eletrolitico: 'capacitor pth eletrolítico radial',
  tempo: 'tempo',
  custo: 'custo',
  preco_venda: 'preço de venda',
})

const getInfos = () => ([
  {
    produto: 'AMPLIF. CLASS D TS 400X4 WATTS',
    carcaca: 0,
    kit_reparo: 0,
    conjunto_magnetico: 0,
    nucleo_toroidal: 1,
    indutor: 1,
    nucleo_carretel: 0,
    placa: 1,
    capacitor_poliester: 4,
    capacitor_eletrolitico: 5,
    tempo: 3,
    custo:  217.83,
    preco_venda: 393.0,
  },
  {
    produto: 'AMPLIF. CLASS D DS 440X4',
    carcaca: 0,
    kit_reparo: 0,
    conjunto_magnetico: 0,
    nucleo_toroidal: 1,
    indutor: 0,
    nucleo_carretel: 1,
    placa: 1,
    capacitor_poliester: 2,
    capacitor_eletrolitico: 6,
    tempo: 4,
    custo: 267.3,
    preco_venda: 483.0,
  },
  {
    produto: 'AMPLIF. CLASS D MD 1200.1 4 OHMS',
    carcaca: 0,
    kit_reparo: 0,
    conjunto_magnetico: 0,
    nucleo_toroidal: 2,
    indutor: 2,
    nucleo_carretel: 0,
    placa: 1,
    capacitor_poliester: 6,
    capacitor_eletrolitico: 2,
    tempo: 6,
    custo: 316.73,
    preco_venda: 569.67,
  },
  {
    produto: 'AMPLIF. CLASS D BASS 800 1 OHM',
    carcaca: 0,
    kit_reparo: 0,
    conjunto_magnetico: 0,
    nucleo_toroidal: 2,
    indutor: 2,
    nucleo_carretel: 0,
    placa: 1,
    capacitor_poliester: 8,
    capacitor_eletrolitico: 10,
    tempo: 4,
    custo: 242.27,
    preco_venda: 436.33,
  },
  {
    produto: 'AMPLAYER 400',
    carcaca: 0,
    kit_reparo: 0,
    conjunto_magnetico: 0,
    nucleo_toroidal: 8,
    indutor: 0,
    nucleo_carretel: 5,
    placa: 2,
    capacitor_poliester: 0,
    capacitor_eletrolitico: 5,
    tempo: 5,
    custo: 402.97,
    preco_venda: 796.33,
  },
  {
    produto: 'ALTO FALANTE 12 BASS 1K6 2+2 OHMS',
    carcaca: 1,
    kit_reparo: 1,
    conjunto_magnetico: 1,
    nucleo_toroidal: 0,
    indutor: 0,
    nucleo_carretel: 0,
    placa: 0,
    capacitor_poliester: 0,
    capacitor_eletrolitico: 0,
    tempo: 3,
    custo: 451.53,
    preco_venda: 746.33,
  },
  {
    produto: 'ALTO FALANTE 5 HD 250S 4 OHMS',
    carcaca: 1,
    kit_reparo: 1,
    conjunto_magnetico: 1,
    nucleo_toroidal: 0,
    indutor: 0,
    nucleo_carretel: 0,
    placa: 0,
    capacitor_poliester: 0,
    capacitor_eletrolitico: 0,
    tempo: 3,
    custo: 418.47,
    preco_venda: 929.67,
  },
  {
    produto: 'ALTO FALANTE 12 ML 570S 4 OHMS',
    carcaca: 1,
    kit_reparo: 1,
    conjunto_magnetico: 1,
    nucleo_toroidal: 0,
    indutor: 0,
    nucleo_carretel: 0,
    placa: 0,
    capacitor_poliester: 0,
    capacitor_eletrolitico: 0,
    tempo: 4,
    custo: 835.63,
    preco_venda: 1376.33,
  },
  {
    produto: 'TOTAIS',
    carcaca: 1000,
    kit_reparo: 1000,
    conjunto_magnetico: 1000,
    nucleo_toroidal: 2000,
    indutor: 2000,
    nucleo_carretel: 2000,
    placa: 2000,
    capacitor_poliester: 5000,
    capacitor_eletrolitico: 7000,
    tempo: 10000,//4800000,
    custo: 1500000.0,
    preco_venda: null,
  },
])